plugins { id 'com.android.application' }
android {
    enableKotlin = false
    namespace 'cn.jingzhuan.lib.office.demo'
    compileSdk 35
    androidResources {
        noCompress += ['docx', 'pptx', 'xlsx']
    }
    defaultConfig {
        applicationId 'cn.jingzhuan.lib.office.demo'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName rootProject.publishedVersion
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
dependencies {
    implementation project(':viewer-online')
}
